// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Pranc1ngPegasus/playwright-go-practice/adapter/crawler/googleworkspace"
	"github.com/Pranc1ngPegasus/playwright-go-practice/adapter/handler"
	"github.com/Pranc1ngPegasus/playwright-go-practice/adapter/server"
	logger2 "github.com/Pranc1ngPegasus/playwright-go-practice/domain/logger"
	tracer2 "github.com/Pranc1ngPegasus/playwright-go-practice/domain/tracer"
	"github.com/Pranc1ngPegasus/playwright-go-practice/infra/client"
	"github.com/Pranc1ngPegasus/playwright-go-practice/infra/configuration"
	"github.com/Pranc1ngPegasus/playwright-go-practice/infra/logger"
	"github.com/Pranc1ngPegasus/playwright-go-practice/infra/tracer"
	"net/http"
)

// Injectors from wire.go:

func initialize() (*app, error) {
	loggerLogger, err := logger.NewLogger()
	if err != nil {
		return nil, err
	}
	configurationConfiguration, err := configuration.NewConfiguration()
	if err != nil {
		return nil, err
	}
	tracerTracer, err := tracer.NewTracer(configurationConfiguration)
	if err != nil {
		return nil, err
	}
	web, err := client.NewWeb()
	if err != nil {
		return nil, err
	}
	login, err := googleworkspace.NewLogin(loggerLogger, tracerTracer, web)
	if err != nil {
		return nil, err
	}
	gmailSafety, err := googleworkspace.NewGmailSafety(loggerLogger, tracerTracer, web)
	if err != nil {
		return nil, err
	}
	googleWorkspace := googleworkspace.NewGoogleWorkspace(tracerTracer, web, login, gmailSafety)
	handlerHandler := handler.NewHandler(configurationConfiguration, googleWorkspace)
	httpServer := server.NewServer(configurationConfiguration, handlerHandler)
	mainApp := &app{
		logger: loggerLogger,
		server: httpServer,
		tracer: tracerTracer,
	}
	return mainApp, nil
}

// wire.go:

type app struct {
	logger logger2.Logger
	server *http.Server
	tracer tracer2.Tracer
}
